language: dart
dart:
  - dev
dart_task:
  - test: --platform vm
  - dartanalyzer: --fatal-warnings lib
matrix:
  include:
    - dart: dev
      dart_task: dartfmt
branches:
  only: [master]
cache:
 directories:
   - $HOME/.pub-cache