language: dart
dart:
  - stable
dart_task:
  - test: --platform vm
  - dartanalyzer: --fatal-warnings lib
  - dartfmt
branches:
  only:
    - master
    - 1.x
cache:
 directories:
   - $HOME/.pub-cache