name: api_client
description: A simple schema api client. Helps to deal with API calls via an API specification
version: 2.1.0
author: Lucas <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-api-client

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  emitter: ^1.0.0
dev_dependencies:
  test: ^1.3.4
  mockito: ^4.0.0
  coveralls: ^5.1.0
